//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlassikaleCursus : Cursus
    {
        public Nullable<System.DateTime> Van { get; set; }
        public Nullable<System.DateTime> Tot { get; set; }
    }
}
