//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstEDM
{
    using System;
    
    public partial class Naam
    {
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
    }
}
